Document: ardb
Title: Debian ardb Manual
Author: <insert document author here>
Abstract: This manual describes what ardb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ardb/ardb.sgml.gz

Format: postscript
Files: /usr/share/doc/ardb/ardb.ps.gz

Format: text
Files: /usr/share/doc/ardb/ardb.text.gz

Format: HTML
Index: /usr/share/doc/ardb/html/index.html
Files: /usr/share/doc/ardb/html/*.html
